### ISSUE TITLE
Support of two file with shared secret

### ISSUE THREAD

**Issue by rickmak** [oursky/devsecops-secret#14]
In some case, I will need to the same secret across two files.

i.e. I will need a SKYEGAR_API_KEY at skygear.yaml and in docker-compose.yml.

**Comment by hidden-dimensions** [comment]
@rickmak how about consolidate them into one `.env` file, then reference them on docker-compose (auto loaded, just add environment entry `ABC=${ABC}`), and yaml (k8s?) with secret map.

otherwise generate `.env` then sed cut the value into the 2 files, but then it require custom post-process scripts.

**Comment by rickmak** [comment]
You are still enforcing/assuming service can load .env. In some case, deployment and framework is not able to load .env.
